version: '3'
services:
  frontend:
    # depends_on: 
    #   - backend
    build: .
    environment:
      - "NODE_ENV=development"
      - "VIRTUAL_HOST=local.imonir.com"
      # - "LETSENCRYPT_HOST=local.imonir.com"
      # - "LETSENCRYPT_EMAIL=imonir.dev@gmail.com"
      - "VIRTUAL_PORT=80"
      # - "VIRTUAL_PORT=443"
    expose:
      - 80
      # - 443

    # network_mode: "bridge"
    networks:
      - imonir
    # ports:
    #   - "4000:4000"
    volumes:
     - .:/home/app
     - node_modules:/home/app/node_modules
volumes: 
  node_modules:
networks:
  imonir:
    external: true
