version: '3'
services:
  frontend:
    build: .
    expose:
      - 80
    volumes:
     - .:/home/app
     - node_modules:/home/app/node_modules
    environment:
      VIRTUAL_PORT: "80"
volumes: 
  node_modules:

networks:
  default:
    external:
      name: fullstack
