version: '3'
services:
  frontend:
    # depends_on: 
    #   - backend
    build: .
    environment:
      - "NODE_ENV=development"
      - "VIRTUAL_HOST=local.imonir.com"
      - "VIRTUAL_PORT=80"
    expose:
      - 80

    network_mode: "bridge"
    # networks:
    #   - imonir
    # ports:
    #   - "4000:4000"
    volumes:
     - .:/home/app
     - /home/app/node_modules
# networks:
#   default:
#     external:
#       name: imonir
