version: '3'
services:
  frontend:
    # depends_on: 
    #   - backend
    build: .
    expose:
      - 80
      # - 443

    # network_mode: "bridge"
    networks:
      - imonir
    # ports:
    #   - "4000:4000"
    volumes:
     - .:/home/app
     - node_modules:/home/app/node_modules
volumes: 
  node_modules:
networks:
  imonir:
    external: true
