version: '3.5'

services:
  front:
    container_name: front
    restart: 'unless-stopped'
    build: .
    expose:
      - 4100
    volumes:
     - .:/home/app
     - front_node_modules:/home/app/node_modules
    env_file:
      - .env.front

volumes:
  front_node_modules:

networks:
  default:
    external:
      name: fullstack
