version: '3'
services:
  frontend:
    environment:
      - "NODE_ENV=development"
      - "VIRTUAL_HOST=local.imonir.com"
      # - "LETSENCRYPT_HOST=local.imonir.com"
      # - "LETSENCRYPT_EMAIL=imonir.dev@gmail.com"
      - "VIRTUAL_PORT=80"
      # - "VIRTUAL_PORT=443"
      # - 443
