version: '3.5'

services:
  imonir_front:
    container_name: imonir_front
    restart: 'unless-stopped'
    build: .
    expose:
      - 4100
    volumes:
     - .:/home/app
     - imonir_front_node_modules:/home/app/node_modules
    env_file:
      - .env.front

volumes:
  imonir_front_node_modules:

networks:
  default:
    external:
      name: fullstack
